var defaults = {
	hidenofood: true,
    colorgardentext: true,
	foodoverlay: true,
	toprightchance: true,
	colorborder: true,
	colorwindow: true,
	waterbutton: true,
	autosnail: false,
	snailchoice: "3",
	automsg: false,
	msg: 'Sprinkles!',
	newspotmsg: false,
	gardenExtraBtns: true,
	biggerBtns: true,
	biggerBtnsSizeW: 12,
	biggerBtnsSizeH: 8,
	newmsgtext: 'Spotted (critter)(pd), thanks!',
	pdtext: ' and got a Pink Diamond',
	samplepd: true,
	samplecritter1: "Field Mouse",
	samplecritter2: "Field Mouse",
	samplecritter3: "Birthday Field Mouse",
	samplecritter4: "",
	debug: false,
	threshold1: 0,
	threshold2: 15,
	threshold3: 30,
	threshold4: 45,
	threshold5: 60,
	threshold1c: "6AA1E6",
	threshold2c: "007f00",
	threshold3c: "bfbf1e",
	threshold4c: "9C6A00",
	threshold5c: "FF0000",
	threshold6c: "B3B3B3",
	threshold1border: "glow",
	threshold2border: "glow",
	threshold3border: "glow",
	threshold4border: "inner",
	threshold5border: "glow",
	threshold6border: "inner",
	TextColorthreshold1c: "FFFFFF",
	TextColorthreshold2c: "FFFFFF",
	TextColorthreshold3c: "FFFE00",
	TextColorthreshold4c: "ffae00",
	TextColorthreshold5c: "FFFFFF",
	TextColorthreshold6c: "000000",
	Windowthreshold1: 0,
	Windowthreshold2: 35,
	Windowthreshold3: 50,
	Windowthreshold4: 65,
	Windowthreshold5: 80,
	Windowthreshold1c: "6AA1E6",
	Windowthreshold2c: "007f00",
	Windowthreshold3c: "bfbf1e",
	Windowthreshold4c: "9C6A00",
	Windowthreshold5c: "FF0000",
	Windowthreshold6c: "B3B3B3",
	WindowTextColorthreshold1c: "FFFFFF",
	WindowTextColorthreshold2c: "FFFFFF",
	WindowTextColorthreshold3c: "FFFE00",
	WindowTextColorthreshold4c: "ffae00",
	WindowTextColorthreshold5c: "FFFFFF",
	WindowTextColorthreshold6c: "000000",
	alchemybutton: false,
	step1choice: "base1",
	step2choice: "dust7",
	step3choice: "item12",
	step4choice: "wand0",
	blocktotal: "No Data",
	blockid: "No Data - You must visit any wildlife page (not a garden, the actual wildlife pages) and re-open this window",
	automushroom: false,
	mushroomgameamount: 0,
	seen: false
}
