var maxtimes = {
"Field Mouse": 60,
"White Mouse": 60,
"Pygmy Mouse": 60,
"Mallard": 60,
"Fox": 60,
"Tortoise": 60,
"Hedgehog": 45,
"Mole": 60,
"Brown Bunny": 50,
"Grey Squirrel": 60,
"Red Squirrel": 20,
"Wren": 60,
"Yellow Wagtail": 60,
"Chaffinch": 60,
"Waxwing": 15,
"Kiwi": 20,
"Cuckoo": 60,
"Raccoon": 60,
"Lop Eared Bunny": 30,
"Hare": 50,
"Singing Bush Lark": 60,
"Skunk": 60,
"Gecko": 60,
"Porcupine": 15,
"Meerkat": 60,
"Roadrunner": 15,
"Camel": 60,
"Armadillo": 50,
"Pink Fairy Armadillo": 20,
"Piglet": 30,
"Ostrich": 40,
"Chipmunk": 50,
"Coyote": 50,
"Badger": 20,
"Wolf": 20,
"Olinguito": 10,
"Nightingale": 20,
"Bee Eater": 60,
"Donkey": 60,
"Elephant": 60,
"Deer": 60,
"Guinea Pig": 45,
"Giraffe": 30,
"Woodpecker": 30,
"Barn Owl": 40,
"Long-Eared Owl": 10,
"Australian King Parrot": 20,
"Magpie": 60,
"Pair of Magpies": 45,
"Jackdaw": 25,
"Zebra": 30,
"Crane": 25,
"Blue Jay": 30,
"Kingfisher": 20,
"Seal": 60,
"King Penguin": 60,
"Puffin": 60,
"Walrus": 60,
"Platypus": 60,
"Otter": 60,
"Sea Lion": 60,
"Seal (Underwater)": 60,
"King Penguin (Underwater)": 60,
"Puffin (Underwater)": 60,
"Walrus (Underwater)": 60,
"Platypus (Underwater)": 60,
"Otter (Underwater)": 60,
"Sea Lion (Underwater)": 60,
"Ferret": 10,
"Meteorat": 60,
"Rockoon": 20,
"Froog": 20,
"Snabbit": 20,
"Ping-Ponguin": 20,
"Llama": 15,
"Chickadee": 45,
"Prairie Dog": 40,
"Aardvark": 30,
"Giant Anteater": 45,
"Tiger": 15,
"Gazelle": 15,
"Leopard": 30,
"Oriole": 30,
"Bandicoot": 20,
"Sugar Glider": 20,
"Wombat": 60,
"Hippopotamus (Underwater)": 45,
"Hippopotamus": 45,
"Kangaroo": 45,
"Wallaby": 30,
"Koala": 20,
"Tasmanian Devil": 2,
"Giant Panda": 2,
"Red Panda": 2,
"Gorilla": 2,
"Earthworm": 10, // Seasonal
"Easter Bunny": 60,
"Chocolate Bunny": 60,
"White Chocolate Bunny": 30,
"Dark Chocolate Bunny": 30,
"Red Baby Chick": 5,
"Orange Baby Chick": 5,
"Yellow Baby Chick": 5,
"Green Baby Chick": 5,
"Blue Baby Chick": 5,
"Indigo Baby Chick": 5,
"Violet Baby Chick": 5,
"Rainbow Baby Chick": 5,
"Red Baby Seahorse": 5,
"Orange Baby Seahorse": 5,
"Yellow Baby Seahorse": 5,
"Green Baby Seahorse": 5,
"Blue Baby Seahorse": 5,
"Indigo Baby Seahorse": 5,
"Violet Baby Seahorse": 5,
"Rainbow Baby Seahorse": 5,
"Leprechaun": 60,
"Scuba-Diving Leprechaun": 60,
"Cupid Mouse": 60,
"Pair of Lovebirds": 60,
"Groundhog": 60,
"Robin": 45,
"Cardinal": 60,
"Festive Field Mouse": 60,
"Festive White Mouse": 60,
"Festive Pygmy Mouse": 60,
"Festive Mallard": 60,
"Elf Field Mouse": 60,
"Elf White Mouse": 60,
"Elf Pygmy Mouse": 60,
"Elf Mallard": 60,
"Arctic Fox": 60,
"Arctic Hare": 60,
"Snowy Owl": 30,
"Reindeer": 30,
"Rudolph": 30,
"Polar Bear": 15,
"Peace Dove": 60,
"Merwitch": 60,
"Ghostly Walrus": 60,
"Ghostly Sea-Unicorn": 8,
"Ghostly Boxfish": 15,
"Ghostly Zebrafish": 30,
"Ghostly Loch Ness Monster": 5,
"Ghostly Frog": 15,
"Ghostly Octopus": 30,
"Red Fly": 55,
"Orange Fly": 50,
"Yellow Fly": 45,
"Green Fly": 40,
"Blue Fly": 25,
"Indigo Fly": 10,
"Violet Fly": 5,
"Rainbow Fly": 2,
"Black Cat": 60,
"Bat": 60,
"Ghostly Field Mouse": 60,
"Ghostly White Mouse": 60,
"Ghostly Pygmy Mouse": 60,
"Ghostly Mallard": 60,
"Zombie Field Mouse": 60,
"Zombie White Mouse": 60,
"Zombie Pygmy Mouse": 60,
"Zombie Mallard": 60,
"Crow": 60,
"Pink Dolphin": 10,
"Pink Hippopotamus": 45,
"Pink Panther": 30,
"Pink Elephant": 60,
"Flamingo": 60,
"Summer Field Mouse": 60,
"Summer White Mouse": 60,
"Summer Pygmy Mouse": 60,
"Summer Mallard": 60,
"Red Bee": 30,
"Orange Bee": 30,
"Yellow Bee": 30,
"Green Bee": 20,
"Blue Bee": 20,
"Indigo Bee": 10,
"Violet Bee": 5,
"Rainbow Queen Bee": 2,
"Honey Badger": 20,
"Black Bear": 60,
"Brown Bear": 60,
"Birthday Chick": 5,
"Water Dragon": 60,				// Myths
"Rainbow Dragon": 60,
"Golden Dragon": 60,
"Griffin": 60,
"Phoenix": 30,
"Pegasus": 20,
"Unicorn": 8,
"Winged Unicorn": 6,
"Black Unicorn": 5,
"White Unicorn": 5,
"Baby Unicorn": 4,
"Golden Unicorn": 4,
"Rainbow Unicorn": 4,
"Toad": 20,
"Macaw": 60,					//RainForest
"Okapi": 60,
"Tree Frog": 60,
"Iguana": 45,
"Sloth": 45,
"Kinkajou": 20,
"Gibbon": 20,
"Toucan": 2,							// Endangered
"Golden Lion Tamarin": 2,
"Golden Dart Frog": 2,
"Cassowary": 2,
"Lemur": 2,
"Tapir": 2,
"Orangutan": 2,								// Hummingbirds
"Antillean Crested Hummingbird": 2,
"Swallow Tailed Hummingbird": 2,
"Broad Billed Hummingbird": 2,
"Violet Headed Hummingbird": 2,
"Violet Sabrewing Hummingbird": 2,
"Saw Billed Hummingbird": 2,
"Blossomcrown Hummingbird": 2,				//Zodiac
"Bull": 60,
"Ram": 60,
"Fish": 60,
"Pelican": 60,
"Sea-Goat": 60,
"Centaur": 60,
"Scorpion": 60,
"Peacock": 60,
"Stork": 60,
"Lion": 60,
"Crab": 60,
"Pushmi-Pullyu": 60,
"Baby Bull": 2,						// Babies
"Father & Baby Bull": 60,
"Baby Anteater": 9,
"Mother & Baby Anteater": 45,
"Baby Lop Eared Bunny": 6,
"Mother & Baby Lop Eared Bunny": 30,
"Baby Ram": 2,
"Father & Baby Ram": 60,
"Baby Sugar Glider": 4,
"Mother & Baby Sugar Glider": 20,
"Baby Badger": 4,
"Mother & Baby Badger": 20,
"Baby Fish": 2,
"Mother & Baby Fish": 60,
"Baby Zebra": 6,
"Mother & Baby Zebra": 30,
"Baby Raccoon": 12,
"Mother & Baby Raccoon": 60,
"Baby Pelican": 2,
"Mother & Baby Pelican": 60,
"Baby Wallaby": 6,
"Mother & Baby Wallaby": 30,
"Baby Meerkat": 14,
"Mother & Baby Meerkat": 60,
"Baby Sea-Goat": 2,
"Mother & Baby Sea-Goat": 60,
"Baby Wombat": 12,
"Mother & Baby Wombat": 60,
"Baby Fox": 18,
"Mother & Baby Fox": 60,
"Baby Centaur": 2,
"Father & Baby Centaur": 60,
"Baby Aardvark": 6,
"Mother & Baby Aardvark": 30,
"Baby Elephant": 18,
"Mother & Baby Elephant": 60,
"Baby Scorpion": 2,
"Mother & Baby Scorpion": 60,
"Baby Gazelle": 3,
"Mother & Baby Gazelle": 15,
"Baby Tortoise": 18,
"Mother & Baby Tortoise": 60,
"Baby Peacock": 2,
"Father & Baby Peacock": 60,
"Baby Kangaroo": 9,
"Mother & Baby Kangaroo": 45,
"Baby Hedgehog": 9,
"Mother & Baby Hedgehog": 45,
"Baby Stork": 2,
"Mother & Baby Stork": 60,
"Baby Camel": 15,
"Mother & Baby Camel": 60,
"Baby Deer": 12,
"Mother & Baby Deer": 60,
"Baby Lion": 2,
"Father & Baby Lion": 60,
"Baby Giraffe": 6,
"Mother & Baby Giraffe": 30,
"Baby Brown Bunny": 10,
"Mother & Baby Brown Bunny": 50,
"Baby Crab": 2,
"Mother & Baby Crab": 60,
"Baby Ferret": 2,
"Mother & Baby Ferret": 10,
"Baby Red Squirrel": 4,
"Mother & Baby Red Squirrel": 20,
"Baby Pushmi-Pullyu": 2,
"Mother & Baby Pushmi-Pullyu": 60,
"Baby Koala": 4,
"Mother & Baby Koala": 20,
"Baby Ostrich": 8,
"Mother & Baby Ostrich": 40,			
"Cuckoo Chick": 5,		
"Wren Chick": 5,							// Chicks
"Yellow Wagtail Chick": 5,
"Chaffinch Chick": 5,	
"Waxwing Chick": 5,	
"Singing Bushlark Chick": 5,	
"Roadrunner Chick": 5,	
"Nightingale Chick": 5,	
"Bee Eater Chick": 5,	
"Woodpecker Chick": 5,	
"Magpie Chick": 5,	
"Jackdaw Chick": 5,	
"Crane Chick": 5,	
"Blue Jay Chick": 5,	
"Kingfisher Chick": 5,	
"Chickadee Chick": 5,	
"Oriole Chick": 5,		
"Wriggly Red Caterpillar": 45,					//Butterflies
"Sunset Dreamer Butterfly": 2,
"Prickly Orange Caterpillar": 45,
"Dancing Firewing Butterfly": 2,
"Mellow Yellow Caterpillar": 45,
"Sunlight Sparklewing Butterfly": 2,
"Minty Green Caterpillar": 45,
"Forest Leafwing Butterfly": 2,
"Baby Blue Caterpillar": 45,
"Mystic River Butterfly": 2,
"Lazy Indigo Caterpillar": 45,
"Moonlight Tranquility Butterfly": 2,
"Fluffy Violet Caterpillar": 45,
"Shimmering Musicwing Butterfly": 2,
"Rainbow Butterfly": 2,
"Silver Fox": 60,							//Albino
"Albino Grey Squirrel": 60,					// These times are same as the base wildlife
"Black Squirrel": 60,
"Albino Brown Bunny": 50,
"Albino Hedgehog": 45,
"Albino Mole": 60,
"Albino Kiwi": 20,
"Albino Raccoon": 60,
"Albino Skunk": 60,
"Albino Chipmunk": 50,
"Black Wolf": 20,
"Albino Badger": 20,
"Black Guinea Pig": 45,
"Black Panther": 30,
"Albino Kangaroo": 45,
"Esteparata The Wise Fairy": 60,								//Fairy Tale
"The First Little Pig": 60,
"The Second Little Pig": 60,
"The Third Little Pig": 60,
"The Big Bad Wolf": 60,
"Auricoma The Golden Fairy": 50,
"Papa Bear": 45,
"Mama Bear": 45,
"Baby Bear": 45,
"Goldilocks": 45,
"Amare The Love Fairy": 40,
"Fairytale Frog": 5,
"Handsome Prince": 5,
"Formosinia The Blossom Fairy": 30,
"Duckling": 5,
"Ugly Duckling": 5,
"Beautiful Swan": 15,
"Viridia The Garden Fairy": 25,
"Cow": 40,
"Jack": 20,
"The Giant": 30,
"Golden Hen": 20,
"Esurienti The Hungry Fairy": 20,
"Small Billy Goat": 40,
"Medium-Sized Billy Goat": 30,
"Big Billy Goat": 20,
"Troll": 60,
"Nivea The Beautiful Fairy": 10,
"Snow White": 60,
"The Evil Queen": 60,
"Blusher": 5,
"Jolly": 5,
"Wheezy": 5,
"Grouchy": 5,
"Prof": 5,
"Snoozy": 5,
"Dozy": 5,
"Mermaid": 60,							// Pond
"Seal": 60,
"King Penguin": 60,
"Puffin": 60,
"Walrus": 60,
"Platypus": 60,
"Otter": 60,
"Sea Lion": 60,
"Hippopotamus": 45,
"Watery Seadragon": 60,
"Rainbow Seadragon": 60,
"Golden Seadragon": 60,
"Griffish": 60,
"Phoenish": 30,
"Sea-Pegasus": 20,
"Sea-Unicorn": 8,
"Red Guppy": 60,
"Red Snapper": 30,
"Orange Guppy": 60,
"Clownfish": 20,
"Yellow Guppy": 60,
"Yellow Boxfish": 15,
"Green Guppy": 60,
"Green Wrasse": 10,
"Blue Guppy": 60,
"Blue Damselfish": 8,
"Indigo Guppy": 60,
"Triggerfish": 5,
"Violet Guppy": 60,
"Tuka Anthias": 3,
"Squirrelfish": 20,
"Zebrafish": 30,
"Hippo Tang": 45,
"Leopard Bush Fish": 30,
"Foxface Rabbitfish": 50,
"Pink Skunk Clownfish": 30,
"Raccoon Butterflyfish": 60,
"Goldfish": 20,
"Angelfish": 20,
"Squid": 15,
"Turtle": 15,
"Dolphin": 10,
"Puffer Fish": 10,
"The Loch Ness Monster": 5,
"Tadpole": 2,
"Froglet": 30,
"Adult Frog": 15,
"Lobster": 30,
"Octopus": 30,
"Catfish": 25,
"Stingray": 20,
"Spider Crab": 15,
"Shrimp": 10,
"Starfish": 5,
"Topiary Grey Squirrel": 60,							// Topiary
"Topiary Skunk": 60,
"Topiary Unicorn": 8,
"Topiary Meerkat": 60,
"Topiary Tortoise": 60,
"Topiary Winged Unicorn": 6,
"Topiary Ostrich": 40,
"Topiary Hedgehog": 45,
"Topiary Black Unicorn": 5,
"Topiary Giraffe": 30,
"Topiary Woodpecker": 30,
"Topiary White Unicorn": 5,
"Topiary Badger": 20,
"Topiary Elephant": 60,
"Topiary Baby Unicorn": 4,
"Topiary Zebra": 30,
"Topiary Crane": 25,
"Topiary Golden Unicorn": 4,
"Topiary Leopard": 30,
"Topiary Kangaroo": 45,
"Topiary Rainbow Unicorn": 4,
"Pyrenean Ibex": 40,									// Extinct
"Passenger Pigeon": 35,
"Western Black Rhino": 30,
"Great Auk": 25,
"Sabre-toothed Cat": 20,
"Moa": 15,
"Woolly Mammoth": 10,
"Dodo": 5,
"Birthday Field Mouse": 60,											// Misc
"Birthday Wriggly Red Caterpillar": 45,
"Birthday Mermaid": 60,
"Birthday Badger": 20,
"Birthday Unicorn": 8,
"Birthday Kinkajou": 20,
"Birthday Wise Fairy": 60,
"Birthday Orangutan": 2,
"Birthday Albino Raccoon": 60,
"Birthday Dodo": 5,
"Birthday Elephant": 60,
"Birthday T-Rex": 2,
"Birthday Tortoise": 60,
"Birthday Froog": 20,
"Birthday Fox": 60,
"Birthday Baby Unicorn": 4,
"Birthday Toad": 20,
"Red Chameleon": 15,
"Orange Chameleon": 10,
"Yellow Chameleon": 10,
"Green Chameleon": 5,
"Blue Chameleon": 5,
"Indigo Chameleon": 2,
"Violet Chameleon": 2,
"Rainbow Chameleon": 2,
													// Candy
"Red Candydevil": 60,
"Orange Candydevil": 60,
"Yellow Candydevil": 60,
"Green Candydevil": 60,
"Blue Candydevil": 60,
"Indigo Candydevil": 60,
"Violet Candydevil": 30,
"Rainbow Candydevil": 10,	
"Red Lollipup": 60,
"Orange Lollipup": 60,
"Yellow Lollipup": 60,
"Green Lollipup": 60,
"Blue Lollipup": 60,
"Indigo Lollipup": 60,
"Violet Lollipup": 30,
"Rainbow Lollipup": 10,
"Red Cherrymole": 60,
"Orange Cherrymole": 60,
"Yellow Cherrymole": 60,
"Green Cherrymole": 60,
"Blue Cherrymole": 60,
"Indigo Cherrymole": 60,
"Violet Cherrymole": 30,	
"Rainbow Cherrymole": 10,
"Red Sweettooth": 60,
"Orange Sweettooth": 60,
"Yellow Sweettooth": 60,
"Green Sweettooth": 60,
"Blue Sweettooth": 60,
"Indigo Sweettooth": 60,
"Violet Sweettooth": 30,
"Rainbow Sweettooth": 10,
"Red Sugarsnout": 60,
"Orange Sugarsnout": 60,
"Yellow Sugarsnout": 60,
"Green Sugarsnout": 60,
"Blue Sugarsnout": 60,
"Indigo Sugarsnout": 60,
"Violet Sugarsnout": 30,
"Rainbow Sugarsnout": 10,
"Red Jellybeak": 60,
"Orange Jellybeak": 60,
"Yellow Jellybeak": 60,
"Green Jellybeak": 60,
"Blue Jellybeak": 60,
"Indigo Jellybeak": 60,
"Violet Jellybeak": 30,
"Rainbow Jellybeak": 10,
"Red Chocobug": 60,
"Orange Chocobug": 60,
"Yellow Chocobug": 60,
"Green Chocobug": 60,
"Blue Chocobug": 60,
"Indigo Chocobug": 60,
"Violet Chocobug": 30,
"Rainbow Chocobug": 10,
										// Dinos
"Diplodocus": 2,
"Stegosaurus": 2,
"Velociraptor": 2,
"Triceratops": 2,
"Spinosaurus": 2,
"Pterodactyl": 2,
"Mosasaurus": 2,
"T-Rex": 2,

										// Alice
"Card Gardener": 30,
"The White Rabbit": 60,
"Dinah": 60,
"Bread and Butterfly": 60,
"Rocking Horse Fly": 60,
"Tweedledum": 60,
"Tweedledee": 60,
"The Dodo": 60,
"The Lory": 60,
"The Mouse": 60,
"The Mad Hatter": 60,
"The March Hare": 60,
"The Dormouse": 60,
"The Knave of Hearts": 60,
"The Queen Of Hearts": 60,
"The King Of Hearts": 60,
"The Cheshire Cat": 60,
"The Mock Turtle": 60,
"The Caterpillar": 60,
										// Gold 
"Gold Macaw": 60,
"Gold Gibbon": 20,
"Gold Hare": 50,
"Gold Fox": 60
};