var mintimes = {
"Field Mouse": 55,
"White Mouse": 55,
"Pygmy Mouse": 55,
"Mallard": 55,
"Fox": 55,
"Tortoise": 55,
"Hedgehog": 30,
"Mole": 55,
"Brown Bunny": 40,
"Grey Squirrel": 50,
"Red Squirrel": 15,
"Wren": 40,
"Yellow Wagtail": 40,
"Chaffinch": 40,
"Waxwing": 5,
"Kiwi": 15,
"Cuckoo": 55,
"Raccoon": 30,
"Lop Eared Bunny": 20,
"Hare": 40,
"Singing Bush Lark": 55,
"Skunk": 45,
"Gecko": 55,
"Porcupine": 10,
"Meerkat": 50,
"Roadrunner": 10,
"Camel": 55,
"Armadillo": 40,
"Pink Fairy Armadillo": 5,
"Piglet": 20,
"Ostrich": 30,
"Chipmunk": 30,
"Coyote": 30,
"Badger": 15,
"Wolf": 10,
"Olinguito": 5,
"Nightingale": 15,
"Bee Eater": 30,
"Donkey": 30,
"Elephant": 55,
"Deer": 30,
"Guinea Pig": 30,
"Giraffe": 20,
"Woodpecker": 20,
"Barn Owl": 20,
"Long-Eared Owl": 2,
"Australian King Parrot": 15,
"Magpie": 30,
"Pair of Magpies": 15,
"Jackdaw": 1,
"Zebra": 20,
"Crane": 1,
"Blue Jay": 15,
"Kingfisher": 15,
"Seal": 55,
"King Penguin": 55,
"Puffin": 55,
"Walrus": 55,
"Platypus": 55,
"Otter": 55,
"Sea Lion": 55,
"Ferret": 5,
"Meteorat": 55,
"Rockoon": 10,
"Froog": 10,
"Snabbit": 10,
"Ping-Ponguin": 10,
"Llama": 10,
"Chickadee": 30,
"Prairie Dog": 30,
"Aardvark": 20,
"Giant Anteater": 15,
"Tiger": 10,
"Gazelle": 10,
"Leopard": 20,
"Oriole": 15,
"Bandicoot": 10,
"Sugar Glider": 10,
"Wombat": 30,
"Hippopotamus": 15,
"Kangaroo": 15,
"Wallaby": 15,
"Koala": 10,
"Tasmanian Devil": 0,
"Giant Panda": 0,
"Red Panda": 0,
"Gorilla": 0,
"Earthworm": 5, // Seasonal
"Easter Bunny": 55,
"Chocolate Bunny": 30,
"White Chocolate Bunny": 15,
"Dark Chocolate Bunny": 15,
"Red Baby Chick": 0,
"Orange Baby Chick": 0,
"Yellow Baby Chick": 0,
"Green Baby Chick": 0,
"Blue Baby Chick": 0,
"Indigo Baby Chick": 0,
"Violet Baby Chick": 0,
"Rainbow Baby Chick": 0,
"Red Baby Seahorse": 0,
"Orange Baby Seahorse": 0,
"Yellow Baby Seahorse": 0,
"Green Baby Seahorse": 0,
"Blue Baby Seahorse": 0,
"Indigo Baby Seahorse": 0,
"Violet Baby Seahorse": 0,
"Rainbow Baby Seahorse": 0,
"Leprechaun": 30,
"Scuba-Diving Leprechaun": 30,
"Cupid Mouse": 55,
"Pair of Lovebirds": 55,
"Groundhog": 30,
"Robin": 30,
"Cardinal": 55,
"Festive Field Mouse": 55,
"Festive White Mouse": 55,
"Festive Pygmy Mouse": 55,
"Festive Mallard": 55,
"Elf Field Mouse": 55,
"Elf White Mouse": 55,
"Elf Pygmy Mouse": 55,
"Elf Mallard": 55,
"Arctic Fox": 55,
"Arctic Hare": 55,
"Snowy Owl": 15,
"Reindeer": 15,
"Rudolph": 15,
"Polar Bear": 5,
"Peace Dove": 55,
"Merwitch": 30,
"Ghostly Walrus": 55,
"Ghostly Sea-Unicorn": 3,
"Ghostly Boxfish": 10,
"Ghostly Zebrafish": 20,
"Ghostly Loch Ness Monster": 2,
"Ghostly Frog": 10,
"Ghostly Octopus": 15,
"Red Fly": 50,
"Orange Fly": 40,
"Yellow Fly": 35,
"Green Fly": 30,
"Blue Fly": 10,
"Indigo Fly": 5,
"Violet Fly": 3,
"Rainbow Fly": 1,
"Black Cat": 55,
"Bat": 55,
"Ghostly Field Mouse": 55,
"Ghostly White Mouse": 55,
"Ghostly Pygmy Mouse": 55,
"Ghostly Mallard": 55,
"Zombie Field Mouse": 55,
"Zombie White Mouse": 55,
"Zombie Pygmy Mouse": 55,
"Zombie Mallard": 55,
"Crow": 55,
"Pink Dolphin": 5,
"Pink Hippopotamus": 15,
"Pink Panther": 20,
"Pink Elephant": 55,
"Flamingo": 55,
"Summer Field Mouse": 55,
"Summer White Mouse": 55,
"Summer Pygmy Mouse": 55,
"Summer Mallard": 55,
"Red Bee": 20,
"Orange Bee": 15,
"Yellow Bee": 10,
"Green Bee": 10,
"Blue Bee": 5,
"Indigo Bee": 5,
"Violet Bee": 2,
"Rainbow Queen Bee": 1,
"Honey Badger": 10,
"Black Bear": 55,
"Brown Bear": 55,
"Birthday Chick": 2,
"Water Dragon": 55,				// Myths
"Rainbow Dragon": 55,
"Golden Dragon": 55,
"Griffin": 30,
"Phoenix": 20,
"Pegasus": 10,
"Unicorn": 3,
"Winged Unicorn": 3,
"Black Unicorn": 2,
"White Unicorn": 2,
"Baby Unicorn": 2,
"Golden Unicorn": 2,
"Rainbow Unicorn": 2,
"Macaw": 55,					//RainForest
"Okapi": 55,
"Tree Frog": 55,
"Iguana": 15,
"Sloth": 15,
"Kinkajou": 10,
"Gibbon": 10,
"Toucan": 0,							// Endangered
"Golden Lion Tamarin": 0,
"Golden Dart Frog": 0,
"Cassowary": 0,
"Lemur": 0,
"Tapir": 0,
"Orangutan": 0,								// Hummingbirds
"Antillean Crested Hummingbird": 0,
"Swallow Tailed Hummingbird": 0,
"Broad Billed Hummingbird": 0,
"Violet Headed Hummingbird": 0,
"Violet Sabrewing Hummingbird": 0,
"Saw Billed Hummingbird": 0,
"Blossomcrown Hummingbird": 0,				//Zodiac
"Bull": 55,
"Ram": 55,
"Fish": 55,
"Pelican": 55,
"Sea-Goat": 55,
"Centaur": 55,
"Scorpion": 55,
"Peacock": 55,
"Stork": 55,
"Lion": 45,
"Crab": 55,
"Pushmi-Pullyu": 55,
"Baby Bull": 1,						// Babies
"Father & Baby Bull": 55,
"Baby Anteater": 3,
"Mother & Baby Anteater": 15,
"Baby Lop Eared Bunny": 4,
"Mother & Baby Lop Eared Bunny": 20,
"Baby Ram": 1,
"Father & Baby Ram": 55,
"Baby Sugar Glider": 2,
"Mother & Baby Sugar Glider": 10,
"Baby Badger": 3,
"Mother & Baby Badger": 15,
"Baby Fish": 1,
"Mother & Baby Fish": 55,
"Baby Zebra": 4,
"Mother & Baby Zebra": 20,
"Baby Raccoon": 6,
"Mother & Baby Raccoon": 30,
"Baby Pelican": 1,
"Mother & Baby Pelican": 55,
"Baby Wallaby": 3,
"Mother & Baby Wallaby": 15,
"Baby Meerkat": 10,
"Mother & Baby Meerkat": 50,
"Baby Sea-Goat": 1,
"Mother & Baby Sea-Goat": 55,
"Baby Wombat": 6,
"Mother & Baby Wombat": 30,
"Baby Fox": 14,
"Mother & Baby Fox": 55,
"Baby Centaur": 1,
"Father & Baby Centaur": 55,
"Baby Aardvark": 4,
"Mother & Baby Aardvark": 20,
"Baby Elephant": 12,
"Mother & Baby Elephant": 55,
"Baby Scorpion": 1,
"Mother & Baby Scorpion": 55,
"Baby Gazelle": 2,
"Mother & Baby Gazelle": 10,
"Baby Tortoise": 12,
"Mother & Baby Tortoise": 55,
"Baby Peacock": 1,
"Father & Baby Peacock": 55,
"Baby Kangaroo": 3,
"Mother & Baby Kangaroo": 15,
"Baby Hedgehog": 6,
"Mother & Baby Hedgehog": 30,
"Baby Stork": 1,
"Mother & Baby Stork": 55,
"Baby Camel": 12,
"Mother & Baby Camel": 55,
"Baby Deer": 6,
"Mother & Baby Deer": 30,
"Baby Lion": 1,
"Father & Baby Lion": 45,
"Baby Giraffe": 4,
"Mother & Baby Giraffe": 20,
"Baby Brown Bunny": 8,
"Mother & Baby Brown Bunny": 40,
"Baby Crab": 1,
"Mother & Baby Crab": 55,
"Baby Ferret": 1,
"Mother & Baby Ferret": 5,
"Baby Red Squirrel": 3,
"Mother & Baby Red Squirrel": 15,
"Baby Pushmi-Pullyu": 1,
"Mother & Baby Pushmi-Pullyu": 55,
"Baby Koala": 2,
"Mother & Baby Koala": 10,
"Baby Ostrich": 6,
"Mother & Baby Ostrich": 30,			
"Cuckoo Chick": 0,		
"Wren Chick": 0,							// Chicks
"Yellow Wagtail Chick": 0,
"Chaffinch Chick": 0,	
"Waxwing Chick": 0,	
"Singing Bushlark Chick": 0,	
"Roadrunner Chick": 0,	
"Nightingale Chick": 0,	
"Bee Eater Chick": 0,	
"Woodpecker Chick": 0,	
"Magpie Chick": 0,	
"Jackdaw Chick": 0,	
"Crane Chick": 0,	
"Blue Jay Chick": 0,	
"Kingfisher Chick": 0,	
"Chickadee Chick": 0,	
"Oriole Chick": 0,		
"Wriggly Red Caterpillar": 30,					//Butterflies
"Sunset Dreamer Butterfly": 0,
"Prickly Orange Caterpillar": 30,
"Dancing Firewing Butterfly": 0,
"Mellow Yellow Caterpillar": 30,
"Sunlight Sparklewing Butterfly": 0,
"Minty Green Caterpillar": 30,
"Forest Leafwing Butterfly": 0,
"Baby Blue Caterpillar": 30,
"Mystic River Butterfly": 0,
"Lazy Indigo Caterpillar": 30,
"Moonlight Tranquility Butterfly": 0,
"Fluffy Violet Caterpillar": 30,
"Shimmering Musicwing Butterfly": 0,
"Rainbow Butterfly": 0,
"Silver Fox": 55,							//Albino
"Albino Grey Squirrel": 50,					// These times are same as the base wildlife
"Black Squirrel": 50,
"Albino Brown Bunny": 40,
"Albino Hedgehog": 30,
"Albino Mole": 55,
"Albino Kiwi": 15,
"Albino Raccoon": 30,
"Albino Skunk": 45,
"Albino Chipmunk": 30,
"Black Wolf": 10,
"Albino Badger": 15,
"Black Guinea Pig": 30,
"Black Panther": 20,
"Albino Kangaroo": 15,
"Esteparata The Wise Fairy": 45,								//Fairy Tale
"The First Little Pig": 45,
"The Second Little Pig": 45,
"The Third Little Pig": 45,
"The Big Bad Wolf": 55,
"Auricoma The Golden Fairy": 35,
"Papa Bear": 30,
"Mama Bear": 30,
"Baby Bear": 30,
"Goldilocks": 30,
"Amare The Love Fairy": 25,
"Fairytale Frog": 0,
"Handsome Prince": 0,
"Formosinia The Blossom Fairy": 15,
"Duckling": 0,
"Ugly Duckling": 0,
"Beautiful Swan": 10,
"Viridia The Garden Fairy": 10,
"Cow": 30,
"Jack": 15,
"The Giant": 20,
"Golden Hen": 15,
"Esurienti The Hungry Fairy": 5,
"Small Billy Goat": 25,
"Medium-Sized Billy Goat": 15,
"Big Billy Goat": 5,
"Troll": 50,
"Nivea The Beautiful Fairy": 5,
"Snow White": 55,
"The Evil Queen": 55,
"Blusher": 2,
"Jolly": 2,
"Wheezy": 2,
"Grouchy": 2,
"Prof": 2,
"Snoozy": 2,
"Dozy": 2,
"Mermaid": 30,							// Pond
"Seal": 55,
"King Penguin": 55,
"Puffin": 55,
"Walrus": 55,
"Platypus": 55,
"Otter": 55,
"Sea Lion": 55,
"Hippopotamus": 15,
"Watery Seadragon": 55,
"Rainbow Seadragon": 55,
"Golden Seadragon": 50,
"Griffish": 30,
"Phoenish": 20,
"Sea-Pegasus": 10,
"Sea-Unicorn": 3,
"Red Guppy": 55,
"Red Snapper": 20,
"Orange Guppy": 55,
"Clownfish": 15,
"Yellow Guppy": 55,
"Yellow Boxfish": 10,
"Green Guppy": 55,
"Green Wrasse": 5,
"Blue Guppy": 55,
"Blue Damselfish": 3,
"Indigo Guppy": 55,
"Triggerfish": 2,
"Violet Guppy": 55,
"Tuka Anthias": 1,
"Squirrelfish": 15,
"Zebrafish": 20,
"Hippo Tang": 15,
"Leopard Bush Fish": 20,
"Foxface Rabbitfish": 40,
"Pink Skunk Clownfish": 20,
"Raccoon Butterflyfish": 30,
"Goldfish": 15,
"Angelfish": 15,
"Squid": 10,
"Turtle": 10,
"Dolphin": 5,
"Puffer Fish": 5,
"The Loch Ness Monster": 2,
"Tadpole": 0,
"Froglet": 15,
"Adult Frog": 10,
"Lobster": 15,
"Octopus": 15,
"Catfish": 15,
"Stingray": 15,
"Spider Crab": 10,
"Shrimp": 5,
"Starfish": 2,
"Topiary Grey Squirrel": 50,							// Topiary
"Topiary Skunk": 45,
"Topiary Unicorn": 3,
"Topiary Meerkat": 50,
"Topiary Tortoise": 50,
"Topiary Winged Unicorn": 3,
"Topiary Ostrich": 30,
"Topiary Hedgehog": 30,
"Topiary Black Unicorn": 2,
"Topiary Giraffe": 20,
"Topiary Woodpecker": 20,
"Topiary White Unicorn": 2,
"Topiary Badger": 15,
"Topiary Elephant": 55,
"Topiary Baby Unicorn": 2,
"Topiary Zebra": 20,
"Topiary Crane": 1,
"Topiary Golden Unicorn": 2,
"Topiary Leopard": 20,
"Topiary Kangaroo": 15,
"Topiary Rainbow Unicorn": 2,
"Pyrenean Ibex": 1,									// Extinct
"Passenger Pigeon": 1,
"Western Black Rhino": 1,
"Great Auk": 1,
"Sabre-toothed Cat": 1,
"Moa": 1,
"Woolly Mammoth": 1,
"Dodo": 1,
"Birthday Field Mouse": 60,											// Misc
"Birthday Wriggly Red Caterpillar": 45,
"Birthday Mermaid": 60,
"Birthday Badger": 20,
"Birthday Unicorn": 8,
"Birthday Kinkajou": 20,
"Birthday Wise Fairy": 60,
"Birthday Orangutan": 2,
"Birthday Albino Raccoon": 60,
"Birthday Dodo": 5,
"Red Chameleon": 10,
"Orange Chameleon": 5,
"Yellow Chameleon": 5,
"Green Chameleon": 2,
"Blue Chameleon": 2,
"Indigo Chameleon": 1,
"Violet Chameleon": 1,
"Rainbow Chameleon": 1,
														//candy
"Red Candydevil": 60,
"Orange Candydevil": 60,
"Yellow Candydevil": 60,
"Green Candydevil": 60,
"Blue Candydevil": 60,
"Indigo Candydevil": 60,
"Violet Candydevil": 30,
"Red Lollipup": 60,
"Orange Lollipup": 60,
"Yellow Lollipup": 60,
"Green Lollipup": 60,
"Blue Lollipup": 60,
"Indigo Lollipup": 60,
"Violet Lollipup": 30,
"Red Cherrymole": 60,
"Orange Cherrymole": 60,
"Yellow Cherrymole": 60,
"Green Cherrymole": 60,
"Blue Cherrymole": 60,
"Indigo Cherrymole": 60,
"Violet Cherrymole": 30,
"Red Sweettooth": 60,
"Orange Sweettooth": 60,
"Yellow Sweettooth": 60,
"Green Sweettooth": 60,
"Blue Sweettooth": 60,
"Indigo Sweettooth": 60,
"Violet Sweettooth": 30,
"Red Sugarsnout": 60,
"Orange Sugarsnout": 60,
"Yellow Sugarsnout": 60,
"Green Sugarsnout": 60,
"Blue Sugarsnout": 60,
"Indigo Sugarsnout": 60,
"Violet Sugarsnout": 30,
"Red Jellybeak": 60,
"Orange Jellybeak": 60,
"Yellow Jellybeak": 60,
"Green Jellybeak": 60,
"Blue Jellybeak": 60,
"Indigo Jellybeak": 60,
"Violet Jellybeak": 30,
"Red Chocobug": 60,
"Orange Chocobug": 60,
"Yellow Chocobug": 60,
"Green Chocobug": 60,
"Blue Chocobug": 60,
"Indigo Chocobug": 60,
"Violet Chocobug": 30
};